#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>

#define EPSILON_0 8.854e-12             // Permittivity of free space in F/m
#define GRAVITATIONAL_ACCELERATION 9.81

void physics();
void newtonLaws();
void capacitor();

int main(void)
{

    printf("Assalam u Alaikum.");
    printf("Welcome to my Applied Physics Project");
    printf("The author of this project is Muhammad Abu Bakar Memon - Student ID: 24K-0826 of section BCS-1D");
    
    int choice  = 0;
    do 
    {
        printf("Please select an option to continue, the availabe CLO's/features to choose from are enlisted below: \n");
        printf("1. Tell me an interesting Physics fact.\n");
        printf("2. Newtons Laws.\n");
        printf("3. Capacitor.\n");
        printf("4. Exit Program.\n");

        scanf("%d", &choice);

            switch (choice) 
            {
                case 1 : 
                    physics();
                    break;
                
                case 2 : 
                    newtonLaws();
                    break;
                
                case 3 :
                    capacitor();
                    break;
                
                case 4 :
                    printf("Exiting program.\n");
                    break;
                
                default :
                    printf("Invalid option was chosen.\n");

            }

    } while (choice != 4) ;

    return 0;

}

void physics()
{

    // we are feeding in some facts of physics into the system

    char **ptr;

    ptr = (char **) malloc(10 * sizeof(char *));
    // we want 10 facts for example

    if (ptr == NULL)
    {
        printf("Memory allocation failed.\n");
        printf("Exiting program.\n");
        return;
    }

    // max lenght of each fact is 100;

    *(ptr + 0) = (char *) calloc(100, sizeof(char));
    strcpy( *(ptr + 0), "Light travels at approximately 299,792,458 meters per second in a vacuum.\n");

    *(ptr + 1) = (char *) calloc(100, sizeof(char));
    strcpy( *(ptr + 1), "The theory of relativity was proposed by Albert Einstein in the early 20th century.");

    *(ptr + 2) = (char *) calloc(100, sizeof(char));
    strcpy( *(ptr + 2), "Quantum mechanics governs the behavior of subatomic particles.");

    *(ptr + 3) = (char *) calloc(100, sizeof(char));
    strcpy( *(ptr + 3), "An object in free fall will accelerate at 9.8 meters per second squared near the Earth's surface.");

    *(ptr + 4) = (char *) calloc(100, sizeof(char));
    strcpy( *(ptr + 4), "Black holes are regions of space where gravity is so strong that not even light can escape.");

    *(ptr + 5) = (char *) calloc(100, sizeof(char));
    strcpy( *(ptr + 5), "The speed of sound in air is approximately 343 meters per second.");

    *(ptr + 6) = (char *) calloc(100, sizeof(char));
    strcpy( *(ptr + 6), "Electromagnetic waves include visible light, radio waves, X-rays, and microwaves."); 

    *(ptr + 7) = (char *) calloc(100, sizeof(char));
    strcpy( *(ptr + 7), "The law of conservation of energy states that energy cannot be created or destroyed, only converted.");

    *(ptr + 8) = (char *) calloc(100, sizeof(char));
    strcpy( *(ptr + 8), "The Earth's magnetic field is generated by the movement of molten iron in its outer core.");

    *(ptr + 9) = (char *) calloc(100, sizeof(char));
    strcpy( *(ptr + 9), "The standard unit of force in physics is the Newton, defined as the force required to accelerate 1 kg by 1 m/s^2.");
    
    srand(time(NULL));

    int r_index = 0 + (rand() % 10);

    printf("Random fact of physics is: %s.\n", *(ptr + r_index));

    for (int m = 0; m < 10; m++)
    {
        free( *(ptr + m));
    }

    free(ptr);
}

void newtonLaws()
{

    int n = 0;

    printf("Please select/choose an option from below to choose from: \n");
    printf("1. Perform a calculation/solve a numerical.\n");
    printf("2. Explore concepts and key definiations regarding the CLO.\n");
    printf("3. Exit.\n");

    scanf("%d", &n);

    if (n == 1)
    {
        printf("Please choose from the list of possible calculation to perform one: \n");

        // 32 is the ASCII code for space character
        char ch = 32;

        printf("a) Resultant Force on an object: \n");
        printf("b) Weight of an object: \n");
        scanf("%d", &ch);

        switch (ch) 
        {
            case 'a' :
            {
                float mass = 0.0;
                float acceleration = 0.0; 

                printf("Please provide us with the mass of your body: \n");
                scanf("%f", &mass);

                printf("Please provide us with the acceleration due to gravity due of your body: \n");
                scanf("%f", &acceleration);

                printf("The resultant force on your body is: %.2f\n", mass * acceleration);
            }

            case 'b':
            {

                float mass = 0.0;

                printf("The weight of the object is %.2f in Newtons.", mass * GRAVITATIONAL_ACCELERATION);
                

            }
        }


    }
    else if (n == 2)
    {

        printf("Please choose from the list of possible concepts to explore from: \n");

        // 32 is the ASCII code for space character
        char ch = 32;

        printf("a) Define Force.\n");
        printf("b) List the Four Fundamental Forces.\n");
        printf("c) Enlist with examples the classes of forces.\n");
        printf("d) What are Un-Balanced Forces.\n");
        printf("e) What are Balanced Forces.\n");
        printf("f) Define Friction.\n");
        printf("g) Define Static Friction.\n");
        printf("h) Define Kinetic/Dynamic Friction.\n");
        printf("i) Define Tension.\n");
        printf("j) Define Spring Force.\n");
        printf("k) Define Normal Force.\n");
        printf("l) Define Air Resistance.\n");
        printf("m) Define Applied Force.\n");
        printf("n) Newton's First Law of Motion.\n");
        printf("o) Newton's Second Law of Motion.\n");
        printf("p) Newton's Third Law of Motion.\n");
        printf("q) Define Inertia.\n");
        printf("r) Define Mass.\n");
        printf("s) Define Weight.\n");
        printf("t) Define Weightlessness.\n");

        scanf("%d", &ch);

        switch (ch) 
        {
            case 'a' :
            {
                printf("Force is the rate of change of momentum.\n");
                printf("Or we can also say that,\n");
                printf("Force is the push or pull that causes the  change in the motion of an object.\n");
            }

            case 'b' :
            {
                printf("The Four Fundamental Forces are: \n");

                printf("Two are what we regulary expersience in our daily lives.\n");
                printf("1) Electromagnetic Force.\n");
                printf("2) Gravitational Force.\n");

                printf("The other two are invisible unless we probe deep inside the neucleus of an atom.\n");
                printf("They are: \n");
                printf("3) Strong Neuclear Force.\n");
                printf("4) Weak Neuclear Force.\n");

            }

            case 'c' :
            {
                printf("Forces can be spllit up into two classes: \n");
                printf("1) Contact Forces.\n");
                printf("Examples include: Friction, Tension, Spring etc.\n");

                printf("2) Field Forces/Action at a distant Force.\n");
                printf("Examples include: Electric Field, Gravitational Field.\n");
            }

            case 'd':
            {
                printf("Unequal unbalanced forces producing an unbalanced force causing motion.\n");
            }

            case 'e':
            {
                printf("Equal Forces in opposite direction produce no motion.\n");
            }

            case 'f': 
            {
                printf("Friction is a Force that opposes or works against the motion of two objects that are touching.\n");
            }

            case 'g':
            {
                printf("Static friction acts to prevent an object from sliding.\n");
            }

            case 'h':
            {
                printf("Kinetic/Dynamic Friction acts to make objects slow down.\n");
            }

            case 'i':
            {
                printf("Tension is the force transmitted from one end of the rope to another.\n");
            }

            case 'j':
            {
                printf("Spring Force is the Force exerted by a compressed or stretched springupon any object that is attached to it.\n");
            }

            case 'k':
            {
               printf("Acts in the direction perpendicular to the contact surface.\n"); 
            }

            case 'l':
            {
                printf("Air Resistance is a special typeof frictional force that acts upon objects as they travel through the air.\n");
            }

            case 'm' :
            {
                printf("An app;ied force is a force that is applied to an object by a person or another object.\n");
            }

            case 'n':
            {
                printf("An object at rest will stay at rest and an object in motion will stay in motion unless acted upon by an external Force.\n");
            }

            case 'o':
            {
                printf("The acceleration of an object is directly propotional to the net force acting on it and inversely propotional to it's mass.\n");
            }

            case 'p':
            {
                printf("If two objects interact the Force F12 exerted by object 1 on object 2 is equal in magnitude but opposite in direction to the force F21 exerted by object 2 on object 1.\n");
            }

            case 'q':
            {
                printf("Inertia is the tendency of an object to resist any attempts to change the object's velocity.\n");
            }

            case 'r':
            {
                printf("Mass is the property of an objevt that specifies how muchinertia the object has.\n");
            }

            case 's':
            {
                printf("The weight of an object id equals to the magnitude of the gravitational force exerted on the object.\n");
            }

            case 't':
            {
                printf("Weightlessness refers to the condition in which an object or person experiences no apparent gravitational force, resulting in the sensation of floating or being free-falling..\n");
            }

        }

    }
    else if (n == 3)
    {
        printf("Exiting program.\n");
        return;
    }
    else
    {
        printf("Invalid option was entered.\n");
    }


}

void capacitor()
{

    int n = 0;

    printf("Please select/choose an option from below to choose from: \n");
    printf("1. Perform a calculation/solve a numerical.\n");
    printf("2. Explore concepts and key definiations regarding the CLO.\n");
    printf("3. Exit.\n");

    scanf("%d", &n);

    if (n == 1)
    {

        double k = 1.0 / (4 * M_PI * EPSILON_0);

        printf("Please choose from the list of possible calculation to perform one: \n");

        // 32 is the ASCII code for space character
        char ch = 32;

        printf("a) Capacitance of a capacitor. \n");
        printf("b) Capacitance of a parallel plate capacitor. \n");
        printf("c) Capacitance of a Cylindrical Capacitor.\n");
        printf("d) Capacitance of a Spherical capacitor.\n");
        printf("e) Energy stored in a parallel plate capacitor.\n");
        printf("f) Electric field in the presence of a dielectric.\n");

        scanf("%d", &ch);

        switch (ch) 
        {

            #define Epsilonnot 8.85*10^5;

            case 'a' :
            {
                float charge = 0.0;
                float potentialdifference = 0.0;

                printf("Please provide us with the charge on your body: \n");
                scanf("%f", &charge);

                printf("Please provide us with the potential difference on your body: \n");
                scanf("%f", &potentialdifference);

                printf("The Capacitance of your body is: %.2f\n", charge * potentialdifference);
            }

            case 'b' :
            {
    	        float area = 0.0;
                float distance = 0.0;

                printf("Please provide us with the area of the two parallel plates on the capacitor (in square meters).\n");
                scanf("%f", &area);

                printf("Please provide the distance of seperation between the two plates of the capacitor (in meters).\n");
                scanf("%f", &distance);

                printf("The capacitance of the parallel plate capacitor is: %.12e Farads.\n", (float) (area * EPSILON_0) / distance);
            }

            case 'c' :
            {
                float length = 0.0;
                float radiusoflargecylinder = 0.0;
                float radiusofsmallcylinder = 0.0;

                printf("Please enter the radius of the larger cylinder: \n");
                scanf("%f", &radiusoflargecylinder);

                printf("Please enter the radius of the smaller cylinder: \n");
                scanf("%df", &radiusofsmallcylinder);
                
                printf("Please enter the a length for the cylinder: \n");
                scanf("%f", &length);

                printf("The capacitance of the cylindrical capacitor is: %.2f\n", (float) (length) / (2 * k * log(radiusoflargecylinder/radiusofsmallcylinder)) );
            }

            case 'd' :
            {
                float radiusoflargesphere = 0.0;
                float radiusofsmallsphere = 0.0;

                printf("Enter the radius of the larger sphere: \n");
                scanf("%d", &radiusoflargesphere);

                printf("Enter the radius of the smaller sphere: \n");
                scanf("%d", &radiusofsmallsphere);

                printf("The capacitance of the sphere is: %.2f\n", (float) (radiusoflargesphere *radiusofsmallsphere) / ( k * (radiusoflargesphere - radiusofsmallsphere) ) );
            }   

            case 'e':
            {

                float capacitance =  0.0;
                float charge = 0.0;

                printf("Enter the capacitance of your capacitor: \n");
                scanf("%d", &capacitance);

                printf("Enter the charge of your capacitor: \n");
                scanf("%d", &charge);

                printf("The energy stored in the capacitor is: %.2f\n", (float) (pow(charge, 2)) / ( 2 * capacitance) );
            
            }
            case 'f':
            {

                float k = 0.0;
                float enot = 0.0;

                printf("Enter the di electric constant for your material: \n");
                scanf("%f", &k);

                printf("Enter the value of electric field previously present in the region: \n");
                scanf("%f", &enot);

                printf("The field in the presence of the  dielectric is: %.2f\n", enot/k );
            }

        }

    }
    else if (n == 2)
    {

        printf("Please choose from the list of possible concepts to explore from: \n");

        // 32 is the ASCII code for space character
        char ch = 32;

        printf("a) Capacitance of a capacitor. \n");
        printf("b) Capacitance of a parallel plate capacitor. \n");
        printf("c) Potential difference in a parallel combination of capacitors.\n");
        printf("d) Key Concept of capacitance in a series commbination of capacitors.\n");
        printf("e) Concept of Energy density in an electric field.\n");
        printf("f) Advantages of dielectrics in capacitors.\n");

        scanf("%d", &ch);

        switch (ch) 
        {

            case 'a' :
            {
                printf("The capacitance of a capacitor is the ratio of the magnitude of the charge on either conductor to the  magnitude of the  potential differencebetween them.");
            }

            case 'b' :
            {
                printf("The capacitance of a parallel plate capacitor is propotional to the area of it's plates, and inversely propotional to the distaance between them.");
            }

            case 'c':
            {
                printf("The individual potential differrence across the capacitors connected  in parallel are all the same and are equalto the potential difference appllied across the combination.");
            }
            case 'd':
            {
                printf("The equivalent capacitance of a series combination in always less than any individual capacitnace in the combination.");
            }
            case 'e':
            {
                printf("Energy desity in an electric field in proppotional to the square of the magnitude of the electric field at a given point.");
            }
            case 'f':
            {
                printf("Increase in capacitance.\n");
                printf("Increase in maximum operating voltage.\n");
                printf("Possible mechanical support between the plates, which allows the plates to be close together without touching, thereby decreasing the distance and increasing the Capacitnace.\n");
            }


        }

    }
    else if (n == 3)
    {
        printf("Exiting Program.\n");
    }
    else
    {
        printf("Invalid option was entered.\n");
    }

}
